/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _KVSTORE_H_RPCGEN
#define _KVSTORE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define KV_MAXLEN 1024

struct kvpair {
	int key;
	char *value;
};
typedef struct kvpair kvpair;

#define KVSTORE_PROG 0x20000001
#define KVSTORE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define POST 1
extern  void * post_1(kvpair *, CLIENT *);
extern  void * post_1_svc(kvpair *, struct svc_req *);
#define GET 2
extern  char ** get_1(int *, CLIENT *);
extern  char ** get_1_svc(int *, struct svc_req *);
extern int kvstore_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define POST 1
extern  void * post_1();
extern  void * post_1_svc();
#define GET 2
extern  char ** get_1();
extern  char ** get_1_svc();
extern int kvstore_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_kvpair (XDR *, kvpair*);

#else /* K&R C */
extern bool_t xdr_kvpair ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_KVSTORE_H_RPCGEN */
