/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "kvstore.h"

bool_t
xdr_kvpair (XDR *xdrs, kvpair *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value, KV_MAXLEN))
		 return FALSE;
	return TRUE;
}
