name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ghc make gcc build-essential libtirpc-dev rpcbind
      
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.4.5' # Use a specific GHC version for reproducibility.
      
      - name: Run build script
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Run test script
        run: |
          chmod +x test.sh
          ./test.sh
